### ISSUE TITLE
Cleanup does not appear to work

### ISSUE THREAD

**Issue by DavidBoyd1** [welcoMattic/kymsu#17]
When running kymsu cleanup - it does not appear to work - that is nothing is removed after doing a update on brew.

have to go into plugins.d and run ./homebrew.sh cleanup for it to work.

**Comment by welcoMattic** [comment]
If @mageekguy can take a look at this problem, it would be nice ;)

**Comment by welcoMattic** [comment]
Ping @mageekguy could you help us on this issue? I tried to fix it without success yesterday :/

**Comment by Bruno21** [comment]
Until the bug is fixed, I'm using this script instead kymsu.sh
cleanup parameter work fine.

```
#!/bin/bash

SCRIPTS_DIR=/Users/bruno/.kymsu/plugins.d

for script in $(ls $SCRIPTS_DIR); do
    if [ -x "$SCRIPTS_DIR/$script" ]; then
         $SCRIPTS_DIR/$script $@
    fi
done


```

**Comment by welcoMattic** [comment]
Thanks @Bruno21, may be I'll use your script, more human readable ;)
