### ISSUE TITLE
mas.sh: line 7: mas: command not found

### ISSUE THREAD

**Issue by iamtodor** [welcoMattic/kymsu#19]
Hello welcoMattic,

I was trying to use your script:
- I downloaded repo
- Installed it with install.sh, here is the output from this command: `KYMSU has been installed. Run kymsu command!`
- Runned `kymsu` and got error:
```
mcbk:kymsu todor$ kymsu
Please, grab a ☕️ , KYMSU keep your working environment up to date!
==================================================
🦄  KYMSU self update
Already up to date.

⚛️  Atom editor will be shiny when you'll be back from your coffee/tea break!
Package Updates Available (0)
└── (empty)

🍺  Homebrew
Already up-to-date.

👨‍⚕  ️The Doc is checking that everything is ok.
Your system is ready to brew.

🍏  Mac App Store updates come fast as lightning
/Users/todor/.kymsu/plugins.d/mas.sh: line 3: mas: command not found

Do you wanna run mas upgrade? (y/n)y
/Users/todor/.kymsu/plugins.d/mas.sh: line 7: mas: command not found

mcbk:kymsu todor$
```
What is it? Is it possible to fix it?

**Comment by Bruno21** [comment]
mas must be installed with homebrew

```
$ brew info mas
mas: stable 1.4.1 (bottled), HEAD
Mac App Store command-line interface
https://github.com/mas-cli/mas
/usr/local/Cellar/mas/1.4.1 (6 files, 10.3MB) *
  Poured from bottle on 2018-02-19 at 19:55:09
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mas.rb
==> Requirements
Build: xcode ✔
==> Options
--HEAD
	Install HEAD version
```

**Comment by iamtodor** [comment]
@Bruno21 thank you for the fast reply. It seems I fixed it :)
What do you think if I suggest you to add this info in the repo to prevent confusion for next users like me?

**Comment by welcoMattic** [comment]
@iamtodor Sorry for the delay, I'm ok to add it in README.md ;) Feel free to open a PR

**Comment by JBallin** [comment]
@iamtodor I noticed that `mas` is listed as a requirement in the README, how do you suggest making it more clear?

**Comment by iamtodor** [comment]
@welcoMattic @JBallin yeah, I forgot to answer in a time. Sorry, it was my inattention. I really had no idea how could we improve `README.md` since that info already exists :)

**Comment by JBallin** [comment]
@iamtodor np! I suggest you close the issue then, as it seems resolved. Cheers.
