### ISSUE TITLE
Homebrew updates should be prepared without sudo but npm should with

### ISSUE THREAD

**Issue by chasylexus** [welcoMattic/kymsu#41]
Hi! Homebrew updates should be prepared without `sudo` but npm — with. So everyone should run `kymsu` and `kymsu cleanup` twise: with `sudo` and without. Could you fix this, for example homebrew plugin commands could be written in forced non-sudo mode.

**Comment by welcoMattic** [comment]
Hi!

I don't think that run `npm` command under sudo is a good idea. It's recommended officially to not.
If you think you need it, feel free open a PR to add this behaviour as an option 😉
