### ISSUE TITLE
Error msgs when installing

### ISSUE THREAD

**Issue by wisdomtooth** [welcoMattic/kymsu#42]
Warning: Permanently added the RSA host key for IP address '52.64.108.95' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by welcoMattic** [comment]
It looks like your SSH key is not recognized by GitHub servers. Please follow https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account
