### ISSUE TITLE
Error: Unknown command: cask

### ISSUE THREAD

**Issue by iamtodor** [welcoMattic/kymsu#43]
Hello,

While running the command `kymsu` I'm getting the following error `Error: Unknown command: cask`.
I found on [stackoverflow](https://stackoverflow.com/a/58337898/5151861) the answer: `You don't need to install cask anymore, you just need homebrew. Try using any cask command `.
Is it correct? Don't we need cask to be installed manually?

Looking forward to hearing back!

**Comment by welcoMattic** [comment]
Hi @iamtodor, yes, if you let the cask plugin enabled, you need `cask` be installed. However, if you do not have `cask`, and you do not need it, you can simply remove the line about `cask` in `./plugins.d/homebrew.sh` : https://github.com/welcoMattic/kymsu/blob/master/plugins.d/homebrew.sh#L6

**Comment by iamtodor** [comment]
@welcoMattic the cask cannot be installed anymore on macos. 
Really sad you closed the issue without any discussion.

**Comment by welcoMattic** [comment]
Oh, really? Sorry I didn't know that. Actually, I'm not working anymore on macOS, so this repo is not maintained.
Can you open a PR to remove the line I linked in my last comment?

**Comment by iamtodor** [comment]
@welcoMattic thank you for reopening the issue :)
If I understand correct based on the following output, we cannot install cask:
```
 ✘ todor@mcbk  ~  brew install caskroom/cask/brew-cask
Error: caskroom/cask was moved. Tap homebrew/cask instead.
 ✘ todor@mcbk  ~  brew install homebrew/cask
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "homebrew/cask".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
```

**Comment by welcoMattic** [comment]
It looks like cask is now totally integrated into Homebrew (https://github.com/Homebrew/homebrew-cask)

**Comment by iamtodor** [comment]
@welcoMattic great, thank you for the clarification, I truly appreciate it!
The PR has been submitted :)

**Comment by welcoMattic** [comment]
Thank you for pointing this bug and for the PR! It's merged ;)
